import test from 'node:test'
import assert from 'node:assert/strict'
import { candidateProfile } from '../src/candidateProfile.js'
import { isAiRelevantJob, matchJobToProfile, retrieveCandidateContext } from '../src/cvMatcher.js'
const job=(o={})=>({job_title:'Computer Vision Engineer',skills:['Python','OpenCV','CNN'],requirements:['object detection'],responsibilities:[],description:'Build real-time computer vision models',application_email:'x@y.com',...o})
test('computer vision role matches CV projects',()=>{const r=matchJobToProfile(job()); assert.ok(r.match_score>=0.7); assert.equal(r.decision,'ACCEPT'); assert.ok(r.relevant_projects.length>0)})
test('LLM RAG role retrieves relevant CV context',()=>{const r=matchJobToProfile(job({job_title:'LLM RAG Engineer',skills:['Python','LLMs','RAG'],description:'Build agentic RAG workflows'})); assert.ok(r.match_score>=0.7); assert.ok(retrieveCandidateContext(job({job_title:'LLM RAG Engineer',skills:['LLMs','RAG']})).some(x=>x.text.includes('Claims Automation')))})
test('data analyst is an AI-career-relevant role',()=>{const r=matchJobToProfile(job({job_title:'Power BI Data Analyst',skills:['Power BI'],requirements:[],responsibilities:[],description:'Create business dashboards'})); assert.equal(r.ai_relevance, true); assert.equal(r.decision,'REVIEW'); assert.ok(r.ai_relevance_score>=0.9)})
test('missing profile/job fails gracefully',()=>{assert.throws(()=>matchJobToProfile(null,candidateProfile),/valid job/); assert.throws(()=>matchJobToProfile(job(),null),/candidate profile/)})


test('semantic skill equivalence is reported without inventing unsupported skills', () => { const r = matchJobToProfile({ job_title: 'AI Engineer', skills: ['Generative AI & LLMs', 'RAG Pipelines', 'FastAPI/Flask', 'Git & Docker', 'LangGraph'], description: 'Build LLM and RAG systems' }); assert.ok(r.matched_skills.some((x) => x.skill === 'Generative AI & LLMs' && x.match_type === 'semantic')); assert.ok(r.missing_skills.includes('LangGraph')); assert.ok(!r.missing_skills.includes('RAG Pipelines')) })
test('representative role calibration', () => { for (const [title, skills, expected] of [['Machine Learning Engineer', ['Python','TensorFlow','PyTorch'], 'ACCEPT'], ['Junior Data Scientist', ['Python','Pandas','NumPy','Machine Learning'], 'ACCEPT'], ['Full-Stack Developer', ['React','Node.js','TypeScript'], 'REJECT']]) { const r = matchJobToProfile({ job_title: title, skills, description: title + ' work building models and analyzing data' }); assert.equal(r.decision, expected) } })
test('compound requirements report supported and missing components separately', () => { const r = matchJobToProfile(job({ skills: ['JavaScript & HTML & CSS'] }), { skills: ['JavaScript'], experience: [], projects: [], education: [], certifications: [] }); assert.deepEqual(r.partial_skills[0].missing, ['HTML', 'CSS']); assert.deepEqual(r.partial_skills[0].evidence, ['JavaScript']) })
test('empty requirements use AI relevance instead of CV coverage', () => { const r = matchJobToProfile({ job_title: 'AI Engineer', skills: [], requirements: [], description: 'Build LLM systems' }); assert.ok(r.ai_relevance_score >= 0.9); assert.equal(r.decision, 'ACCEPT'); assert.equal(r.final_confidence, r.match_score); assert.match(r.reason, /requirements were not structured/) })
test('retrieved context contributes only to an actual requirement score', () => { const r = matchJobToProfile({ job_title: 'AI Engineer', skills: ['RAG'], requirements: ['Prompt Engineering'], description: 'Build RAG workflows' }); assert.ok(r.retrieved_context.length > 0); assert.ok(r.matched_skills.some((item) => item.skill === 'Prompt Engineering')); assert.ok(r.match_score > 0) })
test('profile preserves SQL evidence without claiming spreadsheet or BI tools', () => { assert.ok(candidateProfile.skills.includes('SQL')); assert.ok(!candidateProfile.skills.some((skill) => /power bi|excel/i.test(skill))); const r = matchJobToProfile(job({ job_title: 'Data Analyst', skills: ['Power BI', 'Microsoft Excel', 'SQL'] })); assert.ok(r.missing_skills.includes('Power BI')); assert.ok(r.missing_skills.includes('Microsoft Excel')); assert.ok(r.matched_skills.some((item) => item.skill === 'SQL')) })
test('reason reflects the actual match state', () => { const r = matchJobToProfile(job({ skills: ['Python', 'Docker'] })); assert.match(r.reason, /matched|partial|missing/); assert.match(r.reason, /1 missing requirement/); assert.doesNotMatch(r.reason, /0 unmet requirement/) })
test('AI relevance is independent of CV requirement coverage', () => { const r = matchJobToProfile({ job_title: 'AI Engineer', skills: ['Kubernetes', 'AWS'], requirements: ['Master\'s degree', '5 years experience'], description: 'Build machine learning systems' }); assert.equal(r.ai_relevance, true); assert.notEqual(r.decision, 'REJECT'); assert.ok(r.missing_skills.length > 0); assert.notEqual(r.candidate_fit_score, undefined); assert.notEqual(r.ai_relevance_score, undefined) })
test('AI relevance accepts zero-requirement roles and rejects generic roles', () => { assert.equal(isAiRelevantJob({ job_title: 'Junior AI Developer', description: '', skills: [], requirements: [] }), true); const aiJob = matchJobToProfile({ job_title: 'Junior AI Developer', description: '', skills: [], requirements: [] }); assert.equal(aiJob.ai_relevance, true); assert.equal(aiJob.decision, 'REJECT'); assert.equal(isAiRelevantJob({ job_title: 'Frontend Developer', description: 'Build React applications', skills: ['React'], requirements: [] }), false); assert.equal(matchJobToProfile({ job_title: 'Frontend Developer', description: 'Build React applications', skills: ['React'], requirements: [] }).decision, 'REJECT') })
test('AI relevance recognizes the target role families', () => { for (const title of ['Machine Learning Engineer', 'Deep Learning Engineer', 'NLP Engineer', 'Computer Vision Engineer', 'Junior Data Scientist', 'Data Scientist', 'Data Analyst', 'Generative AI Engineer', 'LLM Engineer', 'RAG Engineer', 'AI Automation Engineer', 'AI Agent Developer']) assert.equal(isAiRelevantJob({ job_title: title, description: '', skills: [], requirements: [] }), true) })
test('generic non-AI roles remain rejected unless responsibilities are meaningful', () => { for (const title of ['Full Stack Developer', 'Frontend Developer', 'Backend Developer', 'Mobile Developer', 'Accountant', 'HR', 'Sales', 'Data Entry Specialist']) assert.equal(isAiRelevantJob({ job_title: title, description: 'Build and maintain ordinary business applications.', skills: [], requirements: [] }), false); assert.equal(isAiRelevantJob({ job_title: 'Full Stack Developer', description: 'Build React and Node applications integrating LLMs and RAG pipelines.', skills: [], requirements: [] }), true); assert.equal(isAiRelevantJob({ job_title: 'Software Engineer', description: 'Develop machine learning pipelines and deploy AI models.', skills: [], requirements: [] }), true) })
test('candidate fit uses strong skill evidence', () => { const r = matchJobToProfile({ job_title: 'Machine Learning Engineer', skills: ['Python', 'TensorFlow', 'PyTorch', 'XGBoost'], requirements: [], description: 'Build machine learning models' }); assert.ok(r.candidate_fit_score >= 0.6); assert.ok(r.final_confidence >= r.ai_relevance_score * 0.4) })
test('candidate fit uses retrieved projects and experience', () => { const r = matchJobToProfile({ job_title: 'LLM Engineer', skills: ['LLMs', 'RAG'], requirements: [], description: 'Build generative AI and RAG systems' }); assert.ok(r.relevant_experience.length > 0); assert.ok(r.relevant_projects.length > 0); assert.ok(r.candidate_fit_score > 0) })
test('semantic CV evidence contributes to candidate fit', () => { const r = matchJobToProfile({ job_title: 'Generative AI Engineer', skills: ['Large Language Models'], requirements: ['Retrieval-Augmented Generation'], description: 'Build LLM applications' }); assert.ok(r.matched_skills.length > 0); assert.ok(r.candidate_fit_score > 0.3) })
test('relevance gate rejects unrelated jobs despite strong CV evidence', () => { const r = matchJobToProfile({ job_title: '.NET Developer', skills: ['C#', 'ASP.NET', 'SQL', 'Azure'], requirements: [], description: 'Build enterprise .NET web services' }); assert.equal(r.ai_relevance, false); assert.equal(r.decision, 'REJECT'); assert.equal(r.ai_relevance_score, 0) })
test('final confidence uses both independent scores', () => { const r = matchJobToProfile({ job_title: 'AI Engineer', skills: ['Python', 'RAG'], requirements: ['LLMs'], description: 'Build AI agent and machine learning systems' }); assert.equal(r.final_confidence, r.match_score); assert.equal(r.final_confidence, Number((0.4 * r.ai_relevance_score + 0.6 * r.candidate_fit_score).toFixed(2))); assert.ok(['HIGH', 'MEDIUM', 'LOW'].includes(r.confidence_level)) })
