import test from 'node:test'
import assert from 'node:assert/strict'
import { candidateProfile } from '../src/candidateProfile.js'
import { matchJobToProfile, retrieveCandidateContext } from '../src/cvMatcher.js'
const job=(o={})=>({job_title:'Computer Vision Engineer',skills:['Python','OpenCV','CNN'],requirements:['object detection'],responsibilities:[],description:'Build real-time computer vision models',application_email:'x@y.com',...o})
test('computer vision role matches CV projects',()=>{const r=matchJobToProfile(job()); assert.ok(r.match_score>=0.7); assert.equal(r.decision,'ACCEPT'); assert.ok(r.relevant_projects.length>0)})
test('LLM RAG role retrieves relevant CV context',()=>{const r=matchJobToProfile(job({job_title:'LLM RAG Engineer',skills:['Python','LLMs','RAG'],description:'Build agentic RAG workflows'})); assert.ok(r.match_score>=0.7); assert.ok(retrieveCandidateContext(job({job_title:'LLM RAG Engineer',skills:['LLMs','RAG']})).some(x=>x.text.includes('Claims Automation')))})
test('unrelated role scores lower',()=>{const r=matchJobToProfile(job({job_title:'Power BI Data Analyst',skills:['Power BI'],requirements:[],responsibilities:[],description:'Create business dashboards'})); assert.equal(r.decision,'REJECT'); assert.ok(r.match_score<0.7)})
test('missing profile/job fails gracefully',()=>{assert.throws(()=>matchJobToProfile(null,candidateProfile),/valid job/); assert.throws(()=>matchJobToProfile(job(),null),/candidate profile/)})


test('semantic skill equivalence is reported without inventing unsupported skills', () => { const r = matchJobToProfile({ job_title: 'AI Engineer', skills: ['Generative AI & LLMs', 'RAG Pipelines', 'FastAPI/Flask', 'Git & Docker', 'LangGraph'], description: 'Build LLM and RAG systems' }); assert.ok(r.matched_skills.some((x) => x.skill === 'Generative AI & LLMs' && x.match_type === 'semantic')); assert.ok(r.missing_skills.includes('LangGraph')); assert.ok(!r.missing_skills.includes('RAG Pipelines')) })
test('representative role calibration', () => { for (const [title, skills, expected] of [['Machine Learning Engineer', ['Python','TensorFlow','PyTorch'], 'ACCEPT'], ['Junior Data Scientist', ['Python','Pandas','NumPy','Machine Learning'], 'ACCEPT'], ['Full-Stack Developer', ['React','Node.js','TypeScript'], 'REJECT']]) { const r = matchJobToProfile({ job_title: title, skills, description: title + ' work building models and analyzing data' }); assert.equal(r.decision, expected) } })
test('compound requirements report supported and missing components separately', () => { const r = matchJobToProfile(job({ skills: ['JavaScript & HTML & CSS'] }), { skills: ['JavaScript'], experience: [], projects: [], education: [], certifications: [] }); assert.deepEqual(r.partial_skills[0].missing, ['HTML', 'CSS']); assert.deepEqual(r.partial_skills[0].evidence, ['JavaScript']) })
test('empty requirements are reviewable rather than scored', () => { const r = matchJobToProfile({ job_title: 'AI Engineer', skills: [], requirements: [], description: 'Build LLM systems' }); assert.equal(r.match_score, null); assert.equal(r.decision, 'REVIEW'); assert.match(r.reason, /could not be extracted/) })
test('retrieved context contributes only to an actual requirement score', () => { const r = matchJobToProfile({ job_title: 'AI Engineer', skills: ['RAG'], requirements: ['Prompt Engineering'], description: 'Build RAG workflows' }); assert.ok(r.retrieved_context.length > 0); assert.ok(r.matched_skills.some((item) => item.skill === 'Prompt Engineering')); assert.ok(r.match_score > 0) })
test('profile preserves SQL evidence without claiming spreadsheet or BI tools', () => { assert.ok(candidateProfile.skills.includes('SQL')); assert.ok(!candidateProfile.skills.some((skill) => /power bi|excel/i.test(skill))); const r = matchJobToProfile(job({ job_title: 'Data Analyst', skills: ['Power BI', 'Microsoft Excel', 'SQL'] })); assert.ok(r.missing_skills.includes('Power BI')); assert.ok(r.missing_skills.includes('Microsoft Excel')); assert.ok(r.matched_skills.some((item) => item.skill === 'SQL')) })
test('reason reflects the actual match state', () => { const r = matchJobToProfile(job({ skills: ['Python', 'Docker'] })); assert.match(r.reason, /matched|partial|missing/); assert.match(r.reason, /1 missing requirement/); assert.doesNotMatch(r.reason, /0 unmet requirement/) })
