import test from 'node:test'
import assert from 'node:assert/strict'
import { extractJob, extractJobDeterministic, extractJobWithLLM, normalizeRequirements, validateJob } from '../src/jobExtractor.js'
const post = "🚀 We're Hiring: AI Engineer | Remote Opportunity\n\nJoin CodeStrat Labs.\n\nSkills:\n✅ Python\n✅ Generative AI & LLMs\n✅ LangChain, LangGraph, LlamaIndex\n✅ RAG Pipelines\n✅ Prompt Engineering\n✅ Vector Databases (Pinecone, FAISS, ChromaDB, Weaviate)\n✅ FastAPI/Flask\n✅ Git & Docker\n📍 Location: Remote\n📩 Apply Now: hiring@codestratlabs.com"
const fake = async () => ({ ok: true, async json() { return { choices: [{ message: { content: JSON.stringify({ job_title: 'AI Engineer | Remote Opportunity', company: 'CodeStrat Labs', location: 'Remote', employment_type: null, experience_level: null, skills: ['Python','Generative AI','Large Language Models','LLMs','LangChain','LangGraph','LlamaIndex','RAG','Prompt Engineering','Pinecone','FAISS','ChromaDB','Weaviate','FastAPI','Flask','Git','Docker'], requirements: [], responsibilities: [], application_email: 'hiring@codestratlabs.com', application_url: null, description: post }) } }] } } })
test('LLM structured extraction preserves explicit job facts and metadata', async () => { const j = await extractJobWithLLM(post, { sourcePostId: 'abc', sourceChannel: '120363427986007778@newsletter' }, { fetchImpl: fake, apiKey: 'test', provider: 'groq', model: 'openai/gpt-oss-20b' }); assert.equal(j.extraction_mode, 'llm'); assert.equal(j.company, 'CodeStrat Labs'); assert.equal(j.location, 'Remote'); assert.equal(j.application_email, 'hiring@codestratlabs.com'); assert.ok(j.skills.includes('LangGraph')); assert.equal(j.source_post_id, 'abc'); assert.equal(j.source_channel, '120363427986007778@newsletter'); assert.equal(j.raw_text, post) })
test('fallback handles missing facts without hallucinating', () => { const j = extractJobDeterministic('AI Engineer needed. Python + ML. Apply at hr@example.com'); assert.equal(j.company, null); assert.equal(j.location, null); assert.equal(j.experience_level, null); assert.equal(j.application_email, 'hr@example.com') })
test('Arabic and URL are preserved', () => { const j = extractJobDeterministic('نبحث عن مهندس ذكاء اصطناعي\nLocation: القاهرة\nApply: https://example.com/jobs/1'); assert.match(j.job_title, /مهندس/); assert.equal(j.application_url, 'https://example.com/jobs/1') })
test('LLM failure falls back and preserves raw text', async () => { const j = await extractJob('AI Engineer. Apply: hr@example.com', {}, { fetchImpl: async () => { throw new Error('timeout') } }); assert.equal(j.extraction_mode, 'deterministic_fallback'); assert.equal(j.raw_text, 'AI Engineer. Apply: hr@example.com'); assert.match(j.extraction_error, /LLM_API_KEY|timeout/) })
test('schema validation rejects missing fields', () => { assert.throws(() => validateJob({}), /Missing job field/) })

test('fallback ignores social introduction and finds role cue', () => { const j = extractJobDeterministic('Dear Connections,\nWe are seeking a motivated Junior Data Scientist to join our team.\nSkills: Python, Pandas'); assert.equal(j.job_title, 'Junior Data Scientist') })
test('fallback supports explicit position cue', () => { const j = extractJobDeterministic('Exciting opportunity!\nPosition: Computer Vision Engineer'); assert.equal(j.job_title, 'Computer Vision Engineer') })
test('fallback extracts labeled lists and generic title/company cues', () => { const j = extractJobDeterministic('Looking for a talented AI Engineer at Plexe AI 🚀\nSkills:\n- Python\n- RAG\nRequirements:\n- Build LLM systems'); assert.equal(j.job_title, 'AI Engineer'); assert.equal(j.company, 'Plexe AI'); assert.deepEqual(j.requirements, ['Build LLM systems']) })
test('fallback extracts company after a role separator', () => { const j = extractJobDeterministic('AI Engineer | CodeStrat Labs and work on cutting-edge AI applications\nRequirements: Python, LLMs'); assert.equal(j.job_title, 'AI Engineer'); assert.equal(j.company, 'CodeStrat Labs'); assert.deepEqual(j.requirements, ['Python', 'LLMs']) })
test('empty LLM arrays recover structured requirements', async () => { const j = await extractJob('AI Engineer\nSkills:\n- Python\n- RAG\nRequirements:\n- Build retrieval systems', {}, { apiKey: 'test', fetchImpl: async () => ({ ok: true, async json() { return { choices: [{ message: { content: JSON.stringify({ job_title: 'AI Engineer', company: null, location: null, employment_type: null, experience_level: null, skills: [], requirements: [], responsibilities: [], application_email: null, application_url: null, description: 'AI Engineer\nSkills:\n- Python\n- RAG\nRequirements:\n- Build retrieval systems' }) } }] } } }) }); assert.deepEqual(j.requirements, ['Build retrieval systems']) })
test('all deterministic requirement labels are recognized', () => { for (const label of ['Skills', 'Requirements', 'Responsibilities', 'Qualifications', 'Experience', 'Education', 'Preferred', 'Location', 'Company', 'Position', 'Role', 'Job Title']) { const j = extractJobDeterministic(`${label}: Python`); assert.ok(j.job_title || label === 'Skills' || label === 'Requirements' || label === 'Responsibilities' || label === 'Qualifications') } })
test('requirements support markdown headings, blank lines, decorations, bullets, and numbers', () => { const j = extractJobDeterministic('AI Engineer\n### Requirements\n\n- Python\n* RAG\n1. Docker\n2. TensorFlow'); assert.deepEqual(j.requirements, ['Python', 'RAG', 'Docker', 'TensorFlow']) })
test('requirements support alternate headings and same-line lists', () => { const j = extractJobDeterministic('Data Scientist\n✅ What we are looking for:\nPython, SQL, TensorFlow\n\nRequired Skills: Pandas, NumPy'); assert.deepEqual(j.requirements, ['Python', 'SQL', 'TensorFlow']); assert.deepEqual(j.skills, ['Pandas', 'NumPy']) })
test('requirements normalize long prose into atomic concepts', () => { assert.deepEqual(normalizeRequirements(['Experience with Python, SQL, REST APIs, Docker and machine learning workflows.']), ['Python', 'SQL', 'REST APIs', 'Docker', 'machine learning']) })
test('LLM and deterministic requirements are merged and deduplicated', async () => { const j = await extractJob('AI Engineer\nRequirements:\n- RAG\n- Python', {}, { apiKey: 'test', fetchImpl: async () => ({ ok: true, async json() { return { choices: [{ message: { content: JSON.stringify({ job_title: 'AI Engineer', company: null, location: null, employment_type: null, experience_level: null, skills: ['Python'], requirements: ['RAG', 'Docker'], responsibilities: [], application_email: null, application_url: null, description: null }) } }] } } }) }); assert.deepEqual(j.requirements, ['RAG', 'Docker', 'Python']); assert.deepEqual(j.skills, []) })
