import test from 'node:test'
import assert from 'node:assert/strict'
import { extractJob, extractJobDeterministic, extractJobWithLLM, validateJob } from '../src/jobExtractor.js'
const post = "🚀 We're Hiring: AI Engineer | Remote Opportunity\n\nJoin CodeStrat Labs.\n\nSkills:\n✅ Python\n✅ Generative AI & LLMs\n✅ LangChain, LangGraph, LlamaIndex\n✅ RAG Pipelines\n✅ Prompt Engineering\n✅ Vector Databases (Pinecone, FAISS, ChromaDB, Weaviate)\n✅ FastAPI/Flask\n✅ Git & Docker\n📍 Location: Remote\n📩 Apply Now: hiring@codestratlabs.com"
const fake = async () => ({ ok: true, async json() { return { choices: [{ message: { content: JSON.stringify({ job_title: 'AI Engineer | Remote Opportunity', company: 'CodeStrat Labs', location: 'Remote', employment_type: null, experience_level: null, skills: ['Python','Generative AI','Large Language Models','LLMs','LangChain','LangGraph','LlamaIndex','RAG','Prompt Engineering','Pinecone','FAISS','ChromaDB','Weaviate','FastAPI','Flask','Git','Docker'], requirements: [], responsibilities: [], application_email: 'hiring@codestratlabs.com', application_url: null, description: post }) } }] } } })
test('LLM structured extraction preserves explicit job facts and metadata', async () => { const j = await extractJobWithLLM(post, { sourcePostId: 'abc', sourceChannel: '120363427986007778@newsletter' }, { fetchImpl: fake, apiKey: 'test', provider: 'groq', model: 'openai/gpt-oss-20b' }); assert.equal(j.extraction_mode, 'llm'); assert.equal(j.company, 'CodeStrat Labs'); assert.equal(j.location, 'Remote'); assert.equal(j.application_email, 'hiring@codestratlabs.com'); assert.ok(j.skills.includes('LangGraph')); assert.equal(j.source_post_id, 'abc'); assert.equal(j.source_channel, '120363427986007778@newsletter'); assert.equal(j.raw_text, post) })
test('fallback handles missing facts without hallucinating', () => { const j = extractJobDeterministic('AI Engineer needed. Python + ML. Apply at hr@example.com'); assert.equal(j.company, null); assert.equal(j.location, null); assert.equal(j.experience_level, null); assert.equal(j.application_email, 'hr@example.com') })
test('Arabic and URL are preserved', () => { const j = extractJobDeterministic('نبحث عن مهندس ذكاء اصطناعي\nLocation: القاهرة\nApply: https://example.com/jobs/1'); assert.match(j.job_title, /مهندس/); assert.equal(j.application_url, 'https://example.com/jobs/1') })
test('LLM failure falls back and preserves raw text', async () => { const j = await extractJob('AI Engineer. Apply: hr@example.com', {}, { fetchImpl: async () => { throw new Error('timeout') } }); assert.equal(j.extraction_mode, 'deterministic_fallback'); assert.equal(j.raw_text, 'AI Engineer. Apply: hr@example.com'); assert.match(j.extraction_error, /LLM_API_KEY|timeout/) })
test('schema validation rejects missing fields', () => { assert.throws(() => validateJob({}), /Missing job field/) })

