const CHANNEL_JID = '120363427986007778@newsletter'
export const JOB_FIELDS = ['job_title', 'company', 'location', 'employment_type', 'experience_level', 'skills', 'requirements', 'responsibilities', 'application_email', 'application_url', 'description', 'source_post_id', 'source_channel', 'raw_text']
export const EXTRACTION_SYSTEM_PROMPT = 'You extract structured job information from a raw job advertisement. Extract only information explicitly supported by the input. Never invent missing facts. Missing scalar values are null and missing lists are []. Preserve meaningful technical skill names. Source metadata is attached by the application.'
const valueAfter = (text, labels) => { const line = text.split(/\r?\n/).find((x) => labels.some((label) => new RegExp(`^\\s*${label}\\s*[:\\-]`, 'i').test(x))); return line ? line.replace(/^\s*[^:\-]+[:\-]\s*/i, '').trim() || null : null }
const listAfter = (text, labels) => { const lines = text.split(/\r?\n/); const i = lines.findIndex((x) => labels.some((label) => new RegExp(`^\\s*${label}\\s*[:\\-]?\\s*$`, 'i').test(x))); if (i < 0) return []; const out = []; for (const x of lines.slice(i + 1)) { if (!/^\s*(?:[-*]|\d+[.)])\s+/.test(x)) break; out.push(x.replace(/^\s*(?:[-*]|\d+[.)])\s+/, '').trim()) } return out }
const inlineListAfter = (text, labels) => { const line = text.split(/\r?\n/).find((x) => labels.some((label) => new RegExp(`^\\s*${label}\\s*[:\\-]\\s*.+`, 'i').test(x))); if (!line) return []; const value = line.replace(/^\s*[^:\-]+[:\-]\s*/i, '').trim(); return value.split(/[,|+]/).map((item) => item.trim()).filter(Boolean) }
const sectionLabels = {
  requirements: ['requirements', 'job requirements', 'requirements & qualifications', 'qualifications', "what we're looking for", 'what we are looking for'],
  skills: ['skills', 'required skills', 'qualifications & skills', 'tech stack', 'technologies'],
  responsibilities: ['responsibilities', 'what you will do', 'what we will do']
}
const cleanSectionLine = (line) => line.trim().replace(/^(?:[#>*\-•\s]|\p{Extended_Pictographic})+/u, '').replace(/[\s:：\-]+$/u, '').trim().toLowerCase().replace(/\s+/g, ' ')
const sectionMatch = (line, labels) => { const cleaned = cleanSectionLine(line); const label = labels.find((item) => cleaned === item); if (label) return { label, value: '' }; const decorated = line.trim().replace(/^(?:[#>*\-•\s]|\p{Extended_Pictographic})+/u, ''); const match = labels.find((item) => new RegExp(`^${item.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\s*[:\-]\s*(.*)$`, 'i').test(decorated)); if (!match) return null; return { label: match, value: decorated.replace(new RegExp(`^${match.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\s*[:\-]\s*`, 'i'), '').trim() } }
const stripListPrefix = (value) => value.trim().replace(/^(?:[-*•]|\d+[.)])\s+/, '').trim()
const splitListValue = (value) => value.split(/[,;|]|\s+\+\s+/i).map((item) => stripListPrefix(item)).filter(Boolean)
const collectSection = (text, labels) => { const lines = text.split(/\r?\n/); for (let i = 0; i < lines.length; i += 1) { const header = sectionMatch(lines[i], labels); if (!header) continue; const values = header.value ? splitListValue(header.value) : []; for (const line of lines.slice(i + 1)) { if (sectionLabels.requirements.concat(sectionLabels.skills, sectionLabels.responsibilities).some((known) => sectionMatch(line, [known]))) break; if (!line.trim()) continue; const value = stripListPrefix(line); if (value) values.push(value) } return values } return [] }
const normalizeRequirement = (value) => String(value ?? '').replace(/^[\s\-•*\d.)]+/, '').replace(/^(?:experience|proficiency|knowledge|familiarity|expertise|strong understanding|hands-on experience)\s+(?:with|in|of)\s+/i, '').replace(/[.!?]+$/, '').replace(/\s+(?:skills?|experience|knowledge|workflows?)$/i, '').trim()
export const normalizeRequirements = (values) => [...new Map(values.flatMap((value) => splitListValue(normalizeRequirement(value)).flatMap((item) => item.split(/\s+and\s+/i).map(normalizeRequirement))).filter((value) => value.length >= 2).map((value) => [value.toLowerCase(), value])).values()]
export function validateJob(job) { for (const field of JOB_FIELDS) if (!(field in job)) throw new Error(`Missing job field: ${field}`); if ((typeof job.job_title !== 'string' && job.job_title !== null) || !Array.isArray(job.skills) || !Array.isArray(job.requirements) || !Array.isArray(job.responsibilities) || typeof job.raw_text !== 'string') throw new Error('Invalid job schema types'); return job }
export function extractJobDeterministic(rawText, { sourcePostId = null, sourceChannel = CHANNEL_JID } = {}) { const text = typeof rawText === 'string' ? rawText.trim() : ''; const first = text.split(/\r?\n/).map((x) => x.trim()).find(Boolean) ?? ''; const roleFromContent = (text) => {
  const lines = text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean)
  for (const line of lines) {
    const lower = line.toLowerCase()
    for (const label of ['position:', 'role:', 'job title:']) {
      if (lower.startsWith(label)) return line.slice(label.length).trim().replace(/[.,;:-]+$/, '') || null
    }
    for (const phrase of ['seeking a ', 'seeking an ', 'looking for a ', 'looking for an ', 'looking for ', 'hiring a ', 'hiring an ', 'hiring ']) {
      const index = lower.indexOf(phrase)
      if (index >= 0) {
        const value = line.slice(index + phrase.length).split(/\s+(?:to|who|with|at)\s+|[|.,:-]/i)[0].trim().replace(/^(?:a|an)\s+/i, '').replace(/^(?:talented|motivated|passionate|experienced)\s+/i, '')
        if (value.length >= 3) return value
      }
    }
  }
  const separator = lines[0]?.split('|')[0]?.replace(/^(?:we'?re hiring|hiring|vacancy)\s*[:\-]?\s*/i, '').trim()
  return separator || null
}
const companyFromContent = (text) => {
  const patterns = [/(?:^|\s)at\s+([A-Z][A-Za-z0-9&.-]*(?:\s+[A-Z][A-Za-z0-9&.-]*)*)(?=\s|$)/, /\|\s*([A-Z][A-Za-z0-9& .-]{2,60})(?:\s+and\s+|\s*[|,.;]|\s*$)/, /@\s*([A-Z][A-Za-z0-9& .-]{2,60})/, /(?:company|employer):\s*([^\n]+)/i, /join\s+([A-Z][A-Za-z0-9& .-]{2,60})/i]
  for (const pattern of patterns) { const match = text.match(pattern); if (match?.[1]) return match[1].trim().replace(/[.,;:-]+$/, '') }
  return null
}
const title = valueAfter(text, ['job title','position','role','title']) ?? roleFromContent(text) ?? (first.replace(/^[^\p{L}\p{N}]*/u, '').replace(/^(dear connections[,!]?|we'?re hiring|hiring|vacancy|exciting opportunity|join our team)\s*[:\-]?\s*/i, '').trim() || null); const email = text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0] ?? null; const url = text.match(/https?:\/\/[^\s)]+/i)?.[0]?.replace(/[.,;]+$/, '') ?? null; const skills = normalizeRequirements(collectSection(text, sectionLabels.skills)); const requirements = normalizeRequirements(collectSection(text, sectionLabels.requirements)); const uniqueRequirements = new Set(requirements.map((item) => item.toLowerCase())); return validateJob({ job_title: title, company: valueAfter(text, ['company','employer']) ?? companyFromContent(text), location: valueAfter(text, ['location','where']), employment_type: valueAfter(text, ['employment type','type']), experience_level: valueAfter(text, ['experience level','experience','seniority']), skills: skills.filter((item) => !uniqueRequirements.has(item.toLowerCase())), requirements, responsibilities: normalizeRequirements(collectSection(text, sectionLabels.responsibilities)), application_email: email, application_url: url, description: text || null, source_post_id: sourcePostId, source_channel: sourceChannel, raw_text: text }) }
function schema() { const nullable = { anyOf: [{ type: 'string' }, { type: 'null' }] }; return { type: 'object', additionalProperties: false, required: ['job_title','company','location','employment_type','experience_level','skills','requirements','responsibilities','application_email','application_url','description'], properties: { job_title: nullable, company: nullable, location: nullable, employment_type: nullable, experience_level: nullable, skills: { type: 'array', items: { type: 'string' } }, requirements: { type: 'array', items: { type: 'string' } }, responsibilities: { type: 'array', items: { type: 'string' } }, application_email: nullable, application_url: nullable, description: nullable } } }
export async function extractJobWithLLM(rawText, metadata = {}, { fetchImpl = fetch, apiKey = process.env.LLM_API_KEY, model = process.env.LLM_MODEL || 'gpt-4o-mini', provider = process.env.LLM_PROVIDER || 'openai' } = {}) { const text = typeof rawText === 'string' ? rawText.trim() : ''; if (!apiKey) throw new Error('LLM_API_KEY is not configured'); if (!['openai', 'groq'].includes(provider)) throw new Error(`Unsupported LLM_PROVIDER: ${provider}`); const response = await fetchImpl(provider === 'groq' ? 'https://api.groq.com/openai/v1/chat/completions' : 'https://api.openai.com/v1/chat/completions', { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model, temperature: 0, messages: [{ role: 'system', content: EXTRACTION_SYSTEM_PROMPT }, { role: 'user', content: text }], response_format: { type: 'json_schema', json_schema: { name: 'job_extraction', strict: true, schema: schema() } } }) }); if (!response.ok) throw new Error(`LLM request failed (${response.status})`); const body = await response.json(); const content = body.choices?.[0]?.message?.content; if (!content) throw new Error('LLM returned no structured content'); const parsed = JSON.parse(content); return validateJob({ ...parsed, source_post_id: metadata.sourcePostId ?? null, source_channel: metadata.sourceChannel ?? CHANNEL_JID, raw_text: text, extraction_mode: 'llm' }) }
export async function extractJob(rawText, metadata = {}, options = {}) { try { const result = await extractJobWithLLM(rawText, metadata, options); const fallback = extractJobDeterministic(rawText, metadata); const descriptionFallback = result.description && result.description !== rawText ? extractJobDeterministic(result.description, metadata) : null; const requirements = normalizeRequirements([...(result.requirements ?? []), ...fallback.requirements, ...(descriptionFallback?.requirements ?? [])]); const requirementKeys = new Set(requirements.map((item) => item.toLowerCase())); result.skills = normalizeRequirements(result.skills ?? []).filter((item) => !requirementKeys.has(item.toLowerCase())); result.requirements = requirements; return result } catch (error) { const fallback = extractJobDeterministic(rawText, metadata); return { ...fallback, extraction_mode: 'deterministic_fallback', extraction_error: error.message } } }


