const CHANNEL_JID = '120363427986007778@newsletter'
export const JOB_FIELDS = ['job_title', 'company', 'location', 'employment_type', 'experience_level', 'skills', 'requirements', 'responsibilities', 'application_email', 'application_url', 'description', 'source_post_id', 'source_channel', 'raw_text']
export const EXTRACTION_SYSTEM_PROMPT = 'You extract structured job information from a raw job advertisement. Extract only information explicitly supported by the input. Never invent missing facts. Missing scalar values are null and missing lists are []. Preserve meaningful technical skill names. Source metadata is attached by the application.'
const valueAfter = (text, labels) => { const line = text.split(/\r?\n/).find((x) => labels.some((l) => new RegExp(`^\\s*${l}\\s*[:\\-]`, 'i').test(x))); return line ? line.replace(/^\s*[^:\-]+[:\-]\s*/i, '').trim() || null : null }
const listAfter = (text, labels) => { const lines = text.split(/\r?\n/); const i = lines.findIndex((x) => labels.some((l) => new RegExp(`^\\s*${l}\\s*[:\\-]?\\s*$`, 'i').test(x))); if (i < 0) return []; const out = []; for (const x of lines.slice(i + 1)) { if (!/^\s*(?:[-•*]|\d+[.)])\s+/.test(x)) break; out.push(x.replace(/^\s*(?:[-•*]|\d+[.)])\s+/, '').trim()) } return out }
export function validateJob(job) { for (const field of JOB_FIELDS) if (!(field in job)) throw new Error(`Missing job field: ${field}`); if ((typeof job.job_title !== 'string' && job.job_title !== null) || !Array.isArray(job.skills) || !Array.isArray(job.requirements) || !Array.isArray(job.responsibilities) || typeof job.raw_text !== 'string') throw new Error('Invalid job schema types'); return job }
export function extractJobDeterministic(rawText, { sourcePostId = null, sourceChannel = CHANNEL_JID } = {}) { const text = typeof rawText === 'string' ? rawText.trim() : ''; const first = text.split(/\r?\n/).map((x) => x.trim()).find(Boolean) ?? ''; const title = valueAfter(text, ['job title','position','role','title']) ?? (first.replace(/^[^\p{L}\p{N}]*/u, '').replace(/^(we'?re hiring|hiring|vacancy)\s*[:\-]?\s*/i, '').trim() || null); const email = text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0] ?? null; const url = text.match(/https?:\/\/[^\s)]+/i)?.[0]?.replace(/[.,;]+$/, '') ?? null; const skillsLine = valueAfter(text, ['skills','tech stack','technologies']); const skills = skillsLine ? skillsLine.split(/[,|+]/).map((x) => x.trim()).filter(Boolean) : listAfter(text, ['skills']); return validateJob({ job_title: title, company: valueAfter(text, ['company','employer']), location: valueAfter(text, ['location','where']), employment_type: valueAfter(text, ['employment type','type']), experience_level: valueAfter(text, ['experience level','experience','seniority']), skills: [...new Map(skills.map((x) => [x.toLowerCase(), x])).values()], requirements: listAfter(text, ['requirements','qualifications']), responsibilities: listAfter(text, ['responsibilities','what you will do','what you’ll do']), application_email: email, application_url: url, description: text || null, source_post_id: sourcePostId, source_channel: sourceChannel, raw_text: text }) }
function schema() { const nullable = { anyOf: [{ type: 'string' }, { type: 'null' }] }; return { type: 'object', additionalProperties: false, required: ['job_title','company','location','employment_type','experience_level','skills','requirements','responsibilities','application_email','application_url','description'], properties: { job_title: nullable, company: nullable, location: nullable, employment_type: nullable, experience_level: nullable, skills: { type: 'array', items: { type: 'string' } }, requirements: { type: 'array', items: { type: 'string' } }, responsibilities: { type: 'array', items: { type: 'string' } }, application_email: nullable, application_url: nullable, description: nullable } } }
export async function extractJobWithLLM(rawText, metadata = {}, { fetchImpl = fetch, apiKey = process.env.LLM_API_KEY, model = process.env.LLM_MODEL || 'gpt-4o-mini', provider = process.env.LLM_PROVIDER || 'openai' } = {}) { const text = typeof rawText === 'string' ? rawText.trim() : ''; if (!apiKey) throw new Error('LLM_API_KEY is not configured'); if (!['openai', 'groq'].includes(provider)) throw new Error(`Unsupported LLM_PROVIDER: ${provider}`); const response = await fetchImpl(provider === 'groq' ? 'https://api.groq.com/openai/v1/chat/completions' : 'https://api.openai.com/v1/chat/completions', { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model, temperature: 0, messages: [{ role: 'system', content: EXTRACTION_SYSTEM_PROMPT }, { role: 'user', content: text }], response_format: { type: 'json_schema', json_schema: { name: 'job_extraction', strict: true, schema: schema() } } }) }); if (!response.ok) throw new Error(`LLM request failed (${response.status})`); const body = await response.json(); const content = body.choices?.[0]?.message?.content; if (!content) throw new Error('LLM returned no structured content'); const parsed = JSON.parse(content); return validateJob({ ...parsed, source_post_id: metadata.sourcePostId ?? null, source_channel: metadata.sourceChannel ?? CHANNEL_JID, raw_text: text, extraction_mode: 'llm' }) }
export async function extractJob(rawText, metadata = {}, options = {}) { try { return await extractJobWithLLM(rawText, metadata, options) } catch (error) { const fallback = extractJobDeterministic(rawText, metadata); return { ...fallback, extraction_mode: 'deterministic_fallback', extraction_error: error.message } } }


